language: haskell

ghc:
  - "7.8"
  - "7.6"

services:
  - rabbitmq

addons:
  apt:
    packages:
    - postgresql-contrib-9.1
    - libicu-dev
  postgresql: "9.1"

script:
  - ./travis.sh

sudo: required

cache:
  directories:
  - $HOME/.cabal
